image: Ubuntu1804 # образ для сборки

stack: node 10.15.1 # окружение

branches:
  only:
    - master # ветка git

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей

build: off

test_script:
  - npm run lint && npm test # скрипт сборки